### ISSUE TITLE
Template App/Azure Auth

### ISSUE THREAD

**Issue by chrishughandrew** [LIDA-Data-Analytics-Team/find-af-webapp#1]
# Issue 1: Template App/AD Auth
## Summary
Here, we need to utilise a template .NET app and configure for Azure authenciation and application architecture.

## Tasks
- [x]  Register the app in Azure AD App Registration: `find-af-webapp`
- [x]  Create the [template app](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#web-options) and save it in the `git` repo.
- [x]  Setup Azure AD, the IDE and the app [to authenticate to Azure resources during _development_](https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication/local-development-dev-accounts?source=recommendations&tabs=azure-portal%2Csign-in-visual-studio%2Ccommand-line) in a security group called: `find-af-webapp-local-dev`
- [x]  ~Configure MVC and class libraries for business and data layers~ (_Not working in VSCode and Overkill right now_)
- [x]  Configure [Automapper](https://www.nuget.org/packages/AutoMapper.Extensions.Microsoft.DependencyInjection/) to map between Data and ViewModels?
- [x]  Ensure DI enabled
- [ ]  Configure KeyVault access? (Required to store the Storage Account Conn string, or can we do this with [Token Credential](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md#shared-access-signature-sas))
- [x]  Configure Azure AD auth (potentially from [a VS template](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-7.0)?) 
- [x] Configure to use with Azure Table Storage 

## Resources
- We'll have VS soon enough 🤞 , but for now, getting setup for [C#](https://code.visualstudio.com/docs/csharp/get-started) and [.NET](https://code.visualstudio.com/docs/languages/dotnet) development on VSCode.
- .NET w/ Keyvault: [Tutorial](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core6x) and [this one with `git` deployment](https://learn.microsoft.com/en-us/azure/key-vault/general/tutorial-net-create-vault-azure-web-app)
- [Managed Identities for AppService](https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#add-a-system-assigned-identity)
- [Managed Identities overview](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) and [utilisation](https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#add-a-system-assigned-identity) and [this detailed guide](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#authenticating-with-defaultazurecredential) on connecting to services with .NET
- Az Table Storage: [HTTP Errors](https://learn.microsoft.com/en-us/rest/api/storageservices/Table-Service-Error-Codes?redirectedfrom=MSDN) and [this strategy](https://stackoverflow.com/questions/3739144/clean-way-to-catch-errors-from-azure-table-other-than-string-match) for error handling.

## Follow up/Further Learning
- Better understand the functionality available in the Azure App Registration
- How to [restrict users](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users) allowed to login through this App Registration. [This guidance](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-apps#assign-users-and-groups-to-roles) might hit the nail.
- Understand the [error handling and logging](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true#error-handling) use cases of Azure.Identity
- Should the Table Storage URI be stored as a secret?

**Comment by chrishughandrew** [comment]
## .NET code template
Created template using the followign bash: 
`dotnet new mvc -auth SingleOrg --client-id <ID> --domain leeds365.onmicrosoft.com --tenant-id <ID> --framework net7.0`


## find-af-webapp registration
From [this quickstart](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-web-app-aspnet-core-sign-in)

**Comment by chrishughandrew** [comment]
## ⚠️  Warning VSCode Users ⚠️ 
 It seems there is an [Issue with the `DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true#defaultazurecredential) when utilising local development authenication via VSCode (rather than the CLI or Visual Studio). It's tracked by [this Github Issuse](https://github.com/Azure/azure-sdk-for-net/issues/30525)
