### ISSUE TITLE
Backend logic

### ISSUE THREAD

**Issue by chrishughandrew** [LIDA-Data-Analytics-Team/find-af-webapp#2]
# Issue 2: Backend logic
## Summary
With the application now configured for use, we can build our backend application logic. This will involve creating the models, then the buisness logic that will process the models and persist any relevant data

## Tasks
- [x]   create a Model object: Prediciton, containing all model input and meta values for peristence 
- [x]   create a interface and service which mocks the API call, returns a json formatted object:  `{score: 0.501}`
  - [x] Refactor this interface to take Request object and Return Response Score object  
- [x]   Create an interface and repository, which adds/persists the Prediction object. A mock repo for Service Unit tests too? 
- [x]   Create an interface/service which:
  - [x]   takes the predictors/meta-data
  - [x]  maps the larger/viewmodel to the JSON `req` and `res` objects
  - [x]   ~authenticates to and~ calls the API (Mock)
  - [x]   persists the input/output
  - [x]   returns the whole object, including score as ViewModel
- [ ]   include useful logging. 
- [ ] Add validation/conversion attributes to:
  - [ ] RequestMlrPredictors
  - [ ]  ResponseMlrScore
  - [x] PredictionTableEntity
  - [ ] PredcitionViewModel

### Storage
- Az Table Storage - [Overview](https://learn.microsoft.com/en-us/azure/storage/tables/table-storage-overview)
- Use [Azure Cosmos for Table](https://learn.microsoft.com/en-us/azure/cosmos-db/table/support?toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fstorage%2Ftables%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json) with [serverless](https://learn.microsoft.com/en-us/azure/cosmos-db/serverless#use-serverless-resources)/consumption plan?  
- [NuGet package](https://www.nuget.org/packages/Azure.Data.Tables/)
- .NET authentication [samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md)
- Defining and adding [strongly typed entities](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample2CreateDeleteEntities.md)

### C#
- [Parameter `null` checking](https://endjin.com/blog/2022/02/csharp-11-preview-parameter-null-checking) in C#11
- Serialising/Deserialising JSON w/ [Newtonsoft](https://www.newtonsoft.com/json/help/html/SerializingJSON.htm)
- [Validation](https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-aspnet-mvc3/cs/adding-validation-to-the-model) in MVC
