### ISSUE TITLE
Prediction Frontend

### ISSUE THREAD

**Issue by chrishughandrew** [LIDA-Data-Analytics-Team/find-af-webapp#3]
# Issue 3: Prediction Frontend
## Summary
With the backend logic now in place, we want to utilise this in our frontend MVC, creating a controller which processes the input of the basic Razor View, passes it to the PredictionSerivce and returns model score alongside an input summary, on a separate View.  

## Tasks
- [ ]  create/utilise a controller for this functionality
- [ ] create controller actions and views for Predict and Score views
- [ ] ensure validation of input values and ModelState validation on failure
- [ ] Dropdowns in views for all inputs (except Age)
- [ ] Use `TempData["predicition"] = data;` to pass values to Summary view. 
- [ ]  ensure authenciation/authorization to the `PredictionController`
- [ ]  ensure only specific Azure Ad users can access site. 
## Resources
